modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Scotsguy/now-playing/issues"
license="MIT"

[[mods]]
modId="nowplaying"
version="${version}"
displayName="Now Playing"
displayURL="https://github.com/Scotsguy/now-playing"
logoFile="assets/now_playing/icon.png"
credits="Thanks to the Forge Team for their work"
authors="AppleTheGolden, JayJay1989BE"
description="Shows a 'now playing' popup whenever a song starts to play."

[[dependencies.nowplaying]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,)"
ordering="NONE"
side="CLIENT"

# TODO: config dependency
