modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/Scotsguy/now-playing/issues"
license="MIT"

[[mods]]
modId="nowplaying"
version="${version}"
displayName="Now Playing"
displayURL="https://github.com/Scotsguy/now-playing"
logoFile="icon.png"
credits="Thanks to the Forge Team for their work"
authors="AppleTheGolden, JayJay1989BE"
description="Shows a 'now playing' popup whenever a song starts to play."

[[dependencies.nowplaying]]
modId="minecraft"
mandatory=true
versionRange="[1.20,)"
ordering="NONE"
side="CLIENT"

[[dependencies.nowplaying]]
modId="cloth_config"
mandatory=true
versionRange="[7,)"
ordering="NONE"
side="CLIENT"
