[versions]
useParchment = "0"
# See https://fabricmc.net/develop/
minecraft = "1.19"
fabric-loader = "0.14.7"
fabric-api = "0.55.3+1.19"

forge = "41.0.16"
# See https://github.com/ParchmentMC/Parchment/wiki/Getting-Started
parchment = "2022.03.13"

quilt-loader = "0.16.0"
quilt-fabric-api = "1.0.0-beta.13+0.51.1-1.18.2"

# See https://maven.shedaniel.me/me/shedaniel/cloth/cloth-config/
cloth-config = "6.2.57"
# See https://github.com/TerraformersMC/ModMenu/releases
modmenu = "3.1.0"

architectury = "4.1.32"
architectury-plugin = "3.4-SNAPSHOT"
loom = "0.11.0-SNAPSHOT"
loom-quiltflower = "1.6.0"
cursegradle = "1.4.0"
shadow = "7.0.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

cloth-common = { module = "me.shedaniel.cloth:cloth-config", version.ref = "cloth-config" }
cloth-fabric = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "cloth-config" }
cloth-forge = { module = "me.shedaniel.cloth:cloth-config-forge", version.ref = "cloth-config" }

quilt-loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt-loader" }
quilt-api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilt-fabric-api" }

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

[plugins]
architectury = { id = "architectury-plugin", version.ref = "architectury-plugin" }
loom = { id = "dev.architectury.loom", version.ref = "loom" }
quiltflower = { id = "io.github.juuxel.loom-quiltflower", version.ref = "loom-quiltflower" }
cursegradle = { id = "com.matthewprenger.cursegradle", version.ref = "cursegradle" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
