on:
  push:
    tags-ignore:
      - 'v*'
    branches:
      - '*'
  pull_request:

name: Build Mod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --stacktrace
      - name: Upload Fabric Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Fabric
          path: |
          fabric/build/libs/*.jar
          release/now-playing-fabric*.jar
      - name: Upload Forge Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Forge
          path: |
          forge/build/libs/*.jar
          release/now-playing-forge*.jar
